style"gtkwidget"{
xthickness=1
ythickness=1
fg[NORMAL]=@windowtext
fg[PRELIGHT]=@windowtext
fg[SELECTED]=@windowtext
fg[ACTIVE]=@windowtext
fg[INSENSITIVE]=@inactivewindowtext
bg[NORMAL]=@window
bg[PRELIGHT]=@window
bg[SELECTED]=@hilight2
bg[ACTIVE]=@hilight2
bg[INSENSITIVE]=@window
base[NORMAL]=@basebg
base[PRELIGHT]=@basebg
base[ACTIVE]=@hilight2
base[SELECTED]=@hilight2
base[INSENSITIVE]=@basebg
text[NORMAL]=@basetext
text[PRELIGHT]=@basetext
text[ACTIVE]=@windowtext
text[SELECTED]=@windowtext
text[INSENSITIVE]=@inactivewindowtext
GtkMenuBar::internal-padding=1
GtkMenuItem::arrow-spacing=5
GtkWidget::link_color=@url
GtkHTML::link-color=@url
GtkIMHtml::hyperlink-color=@url
GnomeHRef::link-color=@url
GtkWidget::visited-link-color=@visitedurl
GtkHTML::visited-link-color=@visitedurl
GtkIMHtml::hyperlink-visited-color=@visitedurl
GtkTreeView::even-row-color=@basebg
GtkTreeView::odd-row-color=@aternatebase
GtkWidget::wide-separators=1
GtkWidget::separator-height=1
GtkWidget::separator-width=1
GtkCheckButton::indicator-size=16
GtkCheckMenuItem::indicator-size=16
GtkRadioButton::indicator-size=16
GtkRadioMenuItem::indicator-size=16
GtkExpander::expander-size=16
GtkWindow::resize-grip-height=0
GtkWindow::resize-grip-width=0
GtkWidget::focus-line-width=0
GtkWidget::focus-padding=0
GtkWidget::interior-focus=0
GtkMenuBar::shadow-type=GTK_SHADOW_NONE
GtkToolbar::shadow-type=GTK_SHADOW_NONE
GtkWidget::shadow-type=GTK_SHADOW_NONE
GtkFrame::shadow-type=GTK_SHADOW_NONE
GtkHandleBox::shadow-type=GTK_SHADOW_NONE
GtkViewport::shadow-type=GTK_SHADOW_NONE
GtkArrow::shadow-type=GTK_SHADOW_NONE
GtkButton::shadow-type=GTK_SHADOW_NONE
GtkMenuItem::shadow-type=GTK_SHADOW_NONE
GtkScrollbar::shadow-type=GTK_SHADOW_NONE
GtkMenu::shadow-type=GTK_SHADOW_NONE
GtkStatusbar::shadow-type=GTK_SHADOW_NONE
GtkWidget::draw-border={0,0,0,0}
GtkButton::inner-border={2,2,2,2}
GtkButton::image-spacing=5
GtkButton::default-outside-border={0,0,0,0}
GtkButton::default-border={0,0,0,0}
GtkEntry::inner-border={2,2,2,2}
GtkScrolledWindow::scrollbar-spacing=0
GtkScrolledWindow::scrollbars-within-bevel=1
GtkProgressBar::min-horizontal-bar-height=7
GtkProgressBar::min-horizontal-bar-width=50
GtkProgressBar::min-vertical-bar-height=50
GtkProgressBar::min-vertical-bar-width=7
GtkNotebook::tab-curvature=0
GtkNotebook::tab-overlap=0
GtkProgressBar::xspacing=0
GtkProgressBar::yspacing=0
GtkMenu::reserve-toggle-size=0
GtkMenu::arrow-placement=GTK_ARROWS_BOTH
GtkMenu::double-arrows=0
GtkIconView::selection-box-alpha=40
GtkIconView::selection-box-color=@hilight
GtkRange::arrow-scaling=1
GtkArrow::arrow-scaling=1
GtkMenuItem::arrow-scaling=1
GtkComboBox::arrow-scaling=1
GtkNotebook::arrow-scaling=1
GtkButton::arrow-scaling=1
GtkScrollbar::arrow-scaling=1
ChromeGtkFrame::frame-color=@window
ChromeGtkFrame::inactive-frame-color=@window
ChromeGtkFrame::frame-gradient-size=0
ChromeGtkFrame::frame-gradient-color=@window
ChromeGtkFrame::scrollbar-trough-color=@window
ChromeGtkFrame::scrollbar-slider-prelight-color=@hilight
ChromeGtkFrame::scrollbar-slider-normal-color=@window
GtkWidget::focus-line-width=0
GtkWidget::focus-padding=0
GtkWidget::interior-focus=0
engine"murrine"{
roundness=2
arrowstyle=0
cellstyle=0
comboboxstyle=0
expanderstyle=0
reliefstyle=0
focusstyle=0
glazestyle=0
glowstyle=4
handlestyle=1
lightborderstyle=1
listviewstyle=0
menubaritemstyle=0
menubarstyle=0
menuitemstyle=0
menustyle=0
textstyle=0
progressbarstyle=0
scrollbarstyle=0 
separatorstyle=0
sliderstyle=0
stepperstyle=1
toolbarstyle=0
###Drawing
contrast=0.0
glazestyle=0
glow_shade=1.0
prelight_shade=1.0
highlight_shade=1.0
lightborder_shade=0.0
border_shades={1.0,1.0}
trough_shades={1.0,1.0}
gradient_shades={1.0,1.0,1.0,1.0}
shadow_shades={0.0,0.0}
#border_colors={"#8a8a8a","#8a8a8a"}
#focus_colors="#ffffff"
#gradient_colors={"#ffffff","#ffffff","#ffffff","#ffffff"}
}}class"GtkWidget"style"gtkwidget"

style "inkscape"{
engine""{}}
widget_class "*SPDesktopWidget" style "inkscape"
widget_class "*SPCanvas*" style "inkscape"
widget_class "*SPButton*" style "inkscape"

style"inkscape2"{
xthickness=5
ythickness=5}
widget_class "*SPDesktopWidget*GtkRadioButton*" style "inkscape2"
widget "*gdl-button*" style "inkscape2"
