style"button"{
xthickness=5
ythickness=5
GtkButton::default-outside-border={0,0,0,0}
GtkButton::default-border={0,0,0,0}
GtkButton::inner-border={1,1,1,1}
GtkButton::shadow-type=GTK_SHADOW_NONE
GtkWidget::wide-separators=0
GtkWidget::separator-height=0
GtkWidget::separator-width=0
engine"pixmap"{
image{
function=BOX
state=INSENSITIVE
shadow=OUT
file="img/button-disabled.png"
border={3,3,3,3}
stretch=TRUE}
image{
function=BOX
state=NORMAL
file="img/button.png"
border={3,3,3,3}
stretch=TRUE}
image{
function=BOX
state=PRELIGHT
shadow=OUT
file="img/button-hover.png"
border={3,3,3,3}
stretch=TRUE}
image{
function=BOX
state=PRELIGHT
shadow=IN
file="img/button-active.png"
border={3,3,3,3}
stretch=TRUE}
image{
function=BOX
state=INSENSITIVE
shadow=IN
file="img/button-active.png"
border={3,3,3,3}
stretch=TRUE}
image{
function=BOX
state=SELECTED
file="img/button-active.png"
border={3,3,3,3}
stretch=TRUE}
image{
function=BOX
state=ACTIVE
file="img/button-active.png"
border={3,3,3,3}
stretch=TRUE}
image{
detail="buttondefault"
file="img/trans.png"
stretch=FALSE}
image{
detail="focus"
file="img/trans.png"
stretch=FALSE}
image{
function=ARROW
state=INSENSITIVE
detail="arrow"
overlay_file="img/arrow_up-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=UP}
image{
function=ARROW
state=INSENSITIVE
overlay_file="img/arrow_down-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=DOWN}
image{
function=ARROW
state=INSENSITIVE
detail="arrow"
overlay_file="img/arrow_left-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=LEFT}
image{
function=ARROW
state=INSENSITIVE
overlay_file="img/arrow_right-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT}
image{
function=ARROW
state=NORMAL
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP}
image{
function=ARROW
state=NORMAL
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN}
image{
function=ARROW
state=NORMAL
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=NORMAL
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=ACTIVE
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=ACTIVE
detail="arrow"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=ACTIVE
detail="arrow"
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=ACTIVE
detail="arrow"
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=PRELIGHT
detail="arrow"
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=PRELIGHT
detail="arrow"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=PRELIGHT
detail="arrow"
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=PRELIGHT
detail="arrow"
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=TAB
state=INSENSITIVE
detail="optionmenutab"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=TAB
state=NORMAL
detail="optionmenutab"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=TAB
state=PRELIGHT
detail="optionmenutab"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=TAB
state=ACTIVE
detail="optionmenutab"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE}}}
class"GtkButton"style"button"
widget_class"*GtkToggleButton"style"button"


style"toolbutton"{
xthickness=3
ythickness=3
GtkButton::default-outside-border={2,2,2,2}
GtkButton::default-border={2,2,2,2}
GtkButton::inner-border={2,2,2,2}
GtkButton::shadow-type=GTK_SHADOW_NONE
GtkWidget::wide-separators=1
GtkWidget::separator-height=0
GtkWidget::separator-width=0
engine"pixmap"{
image{
function=BOX
state=INSENSITIVE
shadow=OUT
file="../theme/img/trans.png"
stretch=FALSE}
image{
function=BOX
state=NORMAL
file="../theme/img/trans.png"
stretch=FALSE}
image{
function=BOX
state=PRELIGHT
shadow=OUT
file="../theme/img/toolbutton-hover.png"
border={2,2,2,2}
stretch=TRUE}
image{
function=BOX
state=PRELIGHT
shadow=IN
file="../theme/img/toolbutton-active-hover.png"
border={2,2,2,2}
stretch=TRUE}
image{
function=BOX
state=INSENSITIVE
shadow=IN
file="../theme/img/toolbutton-active.png"
border={2,2,2,2}
stretch=TRUE}
image{
function=BOX
state=SELECTED
file="../theme/img/toolbutton-active.png"
border={2,2,2,2}
stretch=TRUE}
image{
function=BOX
state=ACTIVE
file="../theme/img/toolbutton-active.png"
border={2,2,2,2}
stretch=TRUE}
image{
detail="buttondefault"
file="../theme/img/trans.png"
stretch=FALSE}
image{
detail="focus"
file="../theme/img/trans.png"
stretch=FALSE}}}
widget_class"*.GtkToolItem*Button"style"toolbutton"
widget_class"*.GtkToolbar*Button"style"toolbutton"
class"*GtkToolButton"style"toolbutton"
class"*GtkToggleToolButton"style"toolbutton"
class"*GtkScaleButton"style"toolbutton"
class"*GtkLinkButton"style"toolbutton"
class"*GimpButton"style"toolbutton"

style"optionmenu"{
xthickness=5
ythickness=5}
widget"*GtkOptionMenu"style"optionmenu"

style"colorbutton"{
GtkButton::inner-border={1,1,2,3}
GtkButton::shadow-type=GTK_SHADOW_NONE}
widget"*GtkColorButton"style"colorbutton"
