style"xfceheaders"{
fg[NORMAL]=@windowtext
fg[PRELIGHT]=@windowtext
fg[SELECTED]=@windowtext
fg[ACTIVE]=@windowtext
fg[INSENSITIVE]=@inactivewindowtext
bg[NORMAL]=@window
bg[PRELIGHT]=@window
bg[SELECTED]=@window
bg[ACTIVE]=@window
bg[INSENSITIVE]=@window
base[NORMAL]=@window
base[PRELIGHT]=@window
base[ACTIVE]=@window
base[SELECTED]=@window
base[INSENSITIVE]=@window
text[NORMAL]=@basetext
text[PRELIGHT]=@basetext
text[ACTIVE]=@windowtext
text[SELECTED]=@windowtext
text[INSENSITIVE]=@inactivewindowtext}
class"*XfceHeading*"style"xfceheaders"
