style"expander"{
xthickness=1
ythickness=1
engine"pixmap"{
image
{
function=EXPANDER
state=NORMAL
expander_style=COLLAPSED
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=PRELIGHT
expander_style=COLLAPSED
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=ACTIVE
expander_style=COLLAPSED
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=INSENSITIVE
expander_style=COLLAPSED
overlay_file="img/arrow_right-insensitive.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=NORMAL
expander_style=SEMI_COLLAPSED
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=PRELIGHT
expander_style=SEMI_COLLAPSED
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=ACTIVE
expander_style=SEMI_COLLAPSED
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=INSENSITIVE
expander_style=SEMI_COLLAPSED
overlay_file="img/arrow_right-insensitive.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=NORMAL
expander_style=EXPANDED
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=PRELIGHT
expander_style=EXPANDED
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=ACTIVE
expander_style=EXPANDED
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=INSENSITIVE
expander_style=EXPANDED
overlay_file="img/arrow_down-insensitive.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=NORMAL
expander_style=SEMI_EXPANDED
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=PRELIGHT
expander_style=SEMI_EXPANDED
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=ACTIVE
expander_style=SEMI_EXPANDED
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=INSENSITIVE
expander_style=SEMI_EXPANDED
overlay_file="img/arrow_down-insensitive.svg"
overlay_stretch=FALSE}}}
widget_class"*GtkExpander"style"expander"
