style"frame"
{
xthickness=0
ythickness=0
engine"pixmap"
{
image
{
function=SHADOW_GAP
shadow=IN
file="img/frame.png"
border={1,1,0,1}
stretch=TRUE
gap_start_file="img/frame-gap_start.png"
gap_start_border={2,0,0,0}
gap_end_file="img/frame-gap_end.png"
gap_end_border={0,2,0,0}
gap_file="img/frame-gap.png"
}
image
{
function=SHADOW_GAP
shadow=ETCHED_IN
file="img/frame.png"
border={1,1,0,1}
stretch=TRUE
gap_start_file="img/frame-gap_start.png"
gap_start_border={2,0,0,0}
gap_end_file="img/frame-gap_end.png"
gap_end_border={0,2,0,0}
gap_file="img/frame-gap.png"
}
image
{
function=SHADOW_GAP
shadow=OUT
file="img/frame.png"
border={1,1,0,1}
stretch=TRUE
gap_start_file="img/frame-gap_start.png"
gap_start_border={2,0,0,0}
gap_end_file="img/frame-gap_end.png"
gap_end_border={0,2,0,0}
gap_file="img/frame-gap.png"
}
image
{
function=SHADOW_GAP
shadow=ETCHED_OUT
file="img/frame.png"
border={1,1,0,1}
stretch=TRUE
gap_start_file="img/frame-gap_start.png"
gap_start_border={2,0,0,0}
gap_end_file="img/frame-gap_end.png"
gap_end_border={0,2,0,0}
gap_file="img/frame-gap.png"
}
image
{
function=SHADOW_GAP
shadow=NONE
file="img/trans.png"
stretch=FALSE
gap_start_file="img/trans.png"
gap_end_file="img/trans.png"
}}}
class"GtkFrame"style"frame"

style"frame2"{
xthickness=0
ythickness=0
fg[NORMAL]=@window
font_name="Sans 0"}
widget_class"*GtkFrame.GtkLabel"style"frame2"

