style "lxpanelwindow"{
xthickness=0
ythickness=0
GtkWidget::shadow-type=GTK_SHADOW_NONE
GtkButton::inner-border={2,2,2,2}
GtkButton::image-spacing=5
engine"pixmap"{
image{
function=BOX
file="img/trans.png"
stretch=FALSE}
image{
function=HANDLE
file="img/trans.png"
stretch=FALSE}
image{
function=SHADOW
shadow=OUT
file="img/trans.png"
border={1,1,0,1}
stretch=TRUE}}}
widget_class "*PanelToplevel*" style "lxpanelwindow"

style"lxpanelbutton"{
xthickness=0
ythickness=0
GtkButton::inner-border={2,2,2,2}
GtkButton::shadow-type=GTK_SHADOW_NONE
GtkWidget::wide-separators=1
GtkWidget::separator-height=0
GtkWidget::separator-width=0
engine"pixmap"{
image{
function=BOX
state=INSENSITIVE
shadow=OUT
file="img/trans.png"
stretch=FALSE}
image{
function=BOX
state=NORMAL
file="img/trans.png"
stretch=FALSE}
image{
function=BOX
state=PRELIGHT
shadow=OUT
file="img/trans.png"
stretch=FALSE}
image{
function=BOX
state=PRELIGHT
shadow=IN
file="img/trans.png"
stretch=FALSE}
image{
function=BOX
state=INSENSITIVE
shadow=IN
file="img/trans.png"
stretch=FALSE}
image{
function=BOX
state=SELECTED
file="img/trans.png"
stretch=FALSE}
image{
function=BOX
state=ACTIVE
file="img/trans.png"
stretch=FALSE}
image{
detail="buttondefault"
file="img/trans.png"
stretch=FALSE}
image{
detail="focus"
file="img/trans.png"
stretch=FALSE}}}
widget_class"*PanelToplevel*Button*"style"lxpanelbutton"

style"lxpaneltask"{
xthickness=3
ythickness=3
GtkButton::inner-border={2,2,2,2}
GtkButton::shadow-type=GTK_SHADOW_NONE
GtkWidget::wide-separators=1
GtkWidget::separator-height=0
GtkWidget::separator-width=0
engine"pixmap"{
image{
function=BOX
state=INSENSITIVE
shadow=OUT
file="img/trans.png"
stretch=FALSE}
image{
function=BOX
state=NORMAL
file="img/trans.png"
stretch=FALSE}
image{
function=BOX
state=PRELIGHT
shadow=OUT
file="img/xfce-panel-task-hover.svg"
stretch=FALSE}
image{
function=BOX
state=PRELIGHT
shadow=IN
file="img/xfce-panel-task-hover.svg"
stretch=FALSE}
image{
function=BOX
state=INSENSITIVE
shadow=IN
file="img/trans.png"
stretch=FALSE}
image{
function=BOX
state=SELECTED
file="img/xfce-panel-task.svg"
stretch=FALSE}
image{
function=BOX
state=ACTIVE
file="img/xfce-panel-task.svg"
stretch=FALSE}
image{
detail="buttondefault"
file="img/trans.png"
stretch=FALSE}
image{
detail="focus"
file="img/trans.png"
stretch=FALSE}}}
widget_class"*PanelToplevel*TaskButton*"style"lxpaneltask"