style"gtknotebook"{
xthickness=2
ythickness=1
GtkNotebook::tab-curvature=5
GtkNotebook::tab-overlap=3
GtkNotebook::has-backward-stepper=0
GtkNotebook::has-forward-stepper=1
GtkNotebook::has-secondary-backward-stepper=1
GtkNotebook::has-secondary-forward-stepper=0
engine"pixmap"{
image{
function=SHADOW
file="img/trans.png"
stretch=FALSE}
image{
function=BOX_GAP
file="img/notebook-top_bg.png"
detail="notebook"
border={1,1,0,1}
stretch=TRUE
gap_file="img/notebook-horizontal_gap.png"
gap_border={1,1,0,0}
gap_start_file="img/notebook_gap.png"
gap_start_border={0,0,0,0}
gap_end_file="img/notebook_gap.png"
gap_end_border={0,0,0,0}
gap_side=TOP}
image{
function=EXTENSION
state=ACTIVE
file="img/notebook-top_tab.png"
border={2,2,2,0}
stretch=TRUE
gap_side=BOTTOM}
image{
function=EXTENSION
file="img/notebook-top_tab-selected.png"
border={3,3,3,0}
stretch=TRUE
gap_side=BOTTOM}
image{
function=BOX_GAP
file="img/notebook-bottom_bg.png"
detail="notebook"
border={1,1,1,0}
stretch=TRUE
gap_file="img/notebook-horizontal_gap.png"
gap_border={1,1,0,0}
gap_start_file="img/notebook_gap.png"
gap_start_border={0,0,0,0}
gap_end_file="img/notebook_gap.png"
gap_end_border={0,0,0,0}
gap_side=BOTTOM}
image{
function=EXTENSION
state=ACTIVE
file="img/notebook-bottom_tab.png"
border={2,2,0,2}
stretch=TRUE
gap_side=TOP}
image{
function=EXTENSION
file="img/notebook-bottom_tab-selected.png"
border={3,3,0,3}
stretch=TRUE
gap_side=TOP}
image{
function=BOX_GAP
file="img/notebook-left_bg.png"
detail="notebook"
border={0,1,1,1}
stretch=TRUE
gap_file="img/notebook-vertical_gap.png"
gap_border={0,0,1,1}
gap_start_file="img/notebook_gap.png"
gap_start_border={0,0,0,0}
gap_end_file="img/notebook_gap.png"
gap_end_border={0,0,0,0}
gap_side=LEFT}
image{
function=EXTENSION
state=ACTIVE
file="img/notebook-left_tab.png"
border={3,0,2,2}
stretch=TRUE
gap_side=RIGHT}
image{
function=EXTENSION
file="img/notebook-left_tab-selected.png"
border={3,1,2,2}
stretch=TRUE
gap_side=RIGHT}
image{
function=BOX_GAP
file="img/notebook-right_bg.png"
detail="notebook"
border={1,0,1,1}
stretch=TRUE
gap_file="img/notebook-vertical_gap.png"
gap_border={0,0,1,1}
gap_start_file="img/notebook_gap.png"
gap_start_border={0,0,0,0}
gap_end_file="img/notebook_gap.png"
gap_end_border={0,0,0,0}
gap_side=RIGHT}
image{
function=EXTENSION
state=ACTIVE
file="img/notebook-right_tab.png"
border={0,3,2,2}
stretch=TRUE
gap_side=LEFT}
image{
function=EXTENSION
file="img/notebook-right_tab-selected.png"
border={1,3,2,2}
stretch=TRUE
gap_side=LEFT}
image
{
function=ARROW
state=INSENSITIVE
overlay_file="img/arrow_up-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=INSENSITIVE
overlay_file="img/arrow_down-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=INSENSITIVE
overlay_file="img/arrow_left-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=INSENSITIVE
overlay_file="img/arrow_right-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=NORMAL
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=NORMAL
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=NORMAL
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=NORMAL
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=ACTIVE
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=ACTIVE

overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=ACTIVE
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=ACTIVE
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=PRELIGHT
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=PRELIGHT
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=PRELIGHT
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=PRELIGHT
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT}}}
class"GtkNotebook"style"gtknotebook"

style"notebooklabel"{
engine"mist"{}}
widget_class"*.<GtkNotebook>.<GtkLabel>"style"notebooklabel"

style"notebooklabelpadding"{
xthickness=5
ythickness=5}
widget_class"*GtkNotebook*GtkEventBox*"style"notebooklabelpadding"
