style"pathbarbutton"{
xthickness=0
ythickness=0
GtkButton::inner-border={5,5,10,10}
GtkButton::shadow-type=GTK_SHADOW_NONE
engine"pixmap"{
image{
function=BOX
state=INSENSITIVE
shadow=OUT
file="img/trans.png"
border={3,3,3,3}
stretch=TRUE}
image{
function=BOX
state=NORMAL
file="img/trans.png"
border={3,3,3,3}
stretch=TRUE}
image{
function=BOX
state=PRELIGHT
shadow=OUT
file="img/button-pathbar-hover.png"
border={3,3,3,3}
stretch=TRUE}
image{
function=BOX
state=PRELIGHT
shadow=IN
file="img/button-pathbar-hover.png"
border={3,3,3,3}
stretch=TRUE}
image{
function=BOX
state=INSENSITIVE
shadow=IN
file="img/trans.png"
border={3,3,3,3}
stretch=TRUE}
image{
function=BOX
state=SELECTED
file="img/trans.png"
border={3,3,3,3}
stretch=TRUE}
image{
function=BOX
state=ACTIVE
file="img/trans.png"
border={3,3,3,3}
stretch=TRUE}
image{
detail="buttondefault"
file="img/trans.png"
stretch=FALSE}
image{
detail="focus"
file="img/trans.png"
}}}
widget_class"*ThunarLocationButtons*GtkButton"style"pathbarbutton"
widget_class"*ThunarLocationButtons*GtkToggleButton"style"pathbarbutton"
widget_class"*GtkPathBar*GtkButton"style"pathbarbutton"

widget_class"*GtkPathBar*GtkToggleButton"style"pathbarbutton"

style"pathbar"{
xthickness=0
ythickness=0}
widget_class"*ThunarLocationButtons"style"pathbar"
