style"progressbar"{
xthickness=0
ythickness=0
font_name="Sans 0"
GtkProgressBar::min-horizontal-bar-height=7
GtkProgressBar::min-horizontal-bar-width=100
GtkProgressBar::min-vertical-bar-height=100
GtkProgressBar::min-vertical-bar-width=7
GtkProgressBar::xspacing=1
GtkProgressBar::yspacing=1
bg[NORMAL]=@window
bg[PRELIGHT]=@window
bg[SELECTED]=@hilight2
bg[ACTIVE]="#b0b0b0"
bg[INSENSITIVE]=@inactivewindowtext
base[NORMAL]=@window
base[PRELIGHT]=@window
base[ACTIVE]=@window
base[SELECTED]=@window
base[INSENSITIVE]=@window
engine"murrine"{
focusstyle=0
contrast=0.0
glazestyle=0
highlight_shade=1.0
roundness=9
border_shades={1.0,1.0}
trough_shades={1.0,1.0}
reliefstyle=0
gradient_shades={1.0,1.0,1.0,1.0}
lightborder_shade=0.0
shadow_shades={0.0,0.0}
border_colors={@hilight2,@hilight2}
}}class"GtkProgressBar"style"progressbar"
