style"radiobox"{
xthickness=0
ythickness=0
fg[NORMAL]=@inactivewindowtext
fg[PRELIGHT]=@inactivewindowtext
fg[SELECTED]=@inactivewindowtext
fg[ACTIVE]=@inactivewindowtext
fg[INSENSITIVE]=@inactivewindowtext
GtkCheckButton::indicator-size=17
GtkCheckButton::indicator-spacing=5
engine"pixmap"{
image{
function=OPTION
state=INSENSITIVE
shadow=OUT
overlay_file="img/radiobox-insensitive.png"
overlay_stretch=FALSE}
image{
function=OPTION
state=NORMAL
shadow=OUT
overlay_file="img/radiobox.png"
overlay_stretch=FALSE}
image{
function=OPTION
state=PRELIGHT
shadow=OUT
overlay_file="img/radiobox-hover.png"
overlay_stretch=FALSE}
image{
function=OPTION
state=ACTIVE
shadow=OUT
overlay_file="img/radiobox-hover.png"
overlay_stretch=FALSE}
## breeze draws tristates as unchecked boxes
image{
function=OPTION
state=INSENSITIVE
shadow=ETCHED_IN
overlay_file="img/radiobox-insensitive.png"
overlay_stretch=FALSE}
image{
function=OPTION
state=NORMAL
shadow=ETCHED_IN
overlay_file="img/radiobox.png"
overlay_stretch=FALSE}
image{
function=OPTION
state=PRELIGHT
shadow=ETCHED_IN
overlay_file="img/radiobox-hover.png"
overlay_stretch=FALSE}
image{
function=OPTION
state=ACTIVE
shadow=ETCHED_IN
overlay_file="img/radiobox-hover.png"
overlay_stretch=FALSE}
image{
function=OPTION
state=INSENSITIVE
shadow=ETCHED_OUT
overlay_file="img/radiobox-insensitive.png"
overlay_stretch=FALSE}
image{
function=OPTION
state=NORMAL
shadow=ETCHED_OUT
overlay_file="img/radiobox.png"
overlay_stretch=FALSE}
image{
function=OPTION
state=PRELIGHT
shadow=ETCHED_OUT
overlay_file="img/radiobox-hover.png"
overlay_stretch=FALSE}
image{
function=OPTION
state=ACTIVE
shadow=ETCHED_OUT
overlay_file="img/radiobox-hover.png"
overlay_stretch=FALSE}
image{
function=OPTION
state=INSENSITIVE
shadow=IN
overlay_file="img/radiobox-checked-insensitive.png"
overlay_stretch=FALSE}
image{
function=OPTION
state=NORMAL
shadow=IN
overlay_file="img/radiobox-checked.png"
overlay_stretch=FALSE}
image{
function=OPTION
state=PRELIGHT
shadow=IN
overlay_file="img/radiobox-checked.png"
overlay_stretch=FALSE}
image{
function=OPTION
state=ACTIVE
shadow=IN
overlay_file="img/radiobox-checked.png"
overlay_stretch=FALSE}}}
class"GtkRadioButton"style"radiobox"
