style"scale"{
xthickness=0
ythickness=0
bg[NORMAL]=@window
bg[PRELIGHT]=@window
bg[SELECTED]=@hilight2
bg[ACTIVE]="#b0b0b0"
bg[INSENSITIVE]=@window
GtkRange::slider-width=18
GtkScale::slider-length=18
GtkScale::trough-side-details=1
GtkRange::trough-border=0
GtkRange::activate-slider=0
engine"murrine"{
focusstyle=0
contrast=0.0
glazestyle=0
highlight_shade=1.0
roundness=9
border_shades={1.0,1.0}
trough_shades={1.0,1.0}
reliefstyle=0
gradient_shades={1.0,1.0,1.0,1.0}
lightborder_shade=0.0
shadow_shades={ 0.0, 0.0 }
border_colors={"#8a8a8a","#8a8a8a"}
gradient_colors={"#fcfcfc","#fcfcfc","#fcfcfc","#fcfcfc"}}}
class"GtkScale"style"scale"

style"gimpscale"{
xthickness=0
ythickness=0
bg[NORMAL]=@basebg
bg[PRELIGHT]=@basebg
bg[SELECTED]=@hilight2
bg[ACTIVE]="#b0b0b0"
bg[INSENSITIVE]=@window}
class"GimpSpinScale"style"gimpscale"
