style"gtkscrolledwindow"{
xthickness=1
ythickness=1
GtkScrolledWindow::scrollbar-spacing=0
GtkScrolledWindow::scrollbars-within-bevel=1
engine"pixmap"{
image{
function=SHADOW
shadow=IN
file="img/shadow.png"
border={1,1,1,1}
stretch=TRUE}
image{
function=SHADOW
shadow=ETCHED_IN
file="img/shadow.png"
border={1,1,1,1}
stretch=TRUE}
image{
function=SHADOW
shadow=OUT
file="img/shadow.png"
border={1,1,1,1}
stretch=TRUE}
image{
function=SHADOW
shadow=ETCHED_OUT
file="img/shadow.png"
border={1,1,1,1}
stretch=TRUE}
image{
function=SHADOW
shadow=NONE
file="img/shadow.png"
stretch=TRUE
border={1,1,1,1}
}}}
class"*GtkScrolledWindow"style"gtkscrolledwindow"
