style "scrollbar"{
bg[NORMAL]=@window
bg[PRELIGHT]=@window
bg[SELECTED]=@window
bg[ACTIVE]=@window
bg[INSENSITIVE]=@window
xthickness=1
ythickness=1
GtkScrollbar::min-slider-length=35
GtkScrollbar::has_secondary_backward_stepper=1
GtkScrollbar::has_secondary_forward_stepper=0
GtkScrollbar::has_backward_stepper=0
GtkScrollbar::has_forward_stepper=1
GtkRange::slider-width=18
GtkRange::stepper-size=18
GtkRange::stepper-spacing=0
GtkRange::trough-border=0
GtkRange::trough-under-steppers=1
engine"pixmap"
{
image
{
function=BOX
orientation=VERTICAL
detail="trough"
file="img/scrollbartrough.png"
border={8,8,10,54}
stretch=TRUE
}
image
{
function=BOX
orientation=HORIZONTAL
detail="trough"
file="img/scrollbartrough_horiz.png"
border={10,54,8,8}
stretch=TRUE
}
image
{
function=SLIDER
state=INSENSITIVE
orientation=VERTICAL
file="img/scrollbarslider.png"
border={8,8,10,10}
stretch=TRUE
}
image
{
function=SLIDER
state=INSENSITIVE
orientation=HORIZONTAL
file="img/scrollbarslider_horiz.png"
border={10,10,8,8}
stretch=TRUE
}
image
{
function=SLIDER
state=NORMAL
orientation=VERTICAL
file="img/scrollbarslider.png"
border={8,8,10,10}
stretch=TRUE
}
image
{
function=SLIDER
state=NORMAL
orientation=HORIZONTAL
file="img/scrollbarslider_horiz.png"
border={10,10,8,8}
stretch=TRUE
}
image
{
function=SLIDER
state=PRELIGHT
orientation=VERTICAL
file="img/scrollbarslider-hover.png"
border={8,8,10,10}
stretch=TRUE
}
image
{
function=SLIDER
state=PRELIGHT
orientation=HORIZONTAL
file="img/scrollbarslider-hover_horiz.png"
border={10,10,8,8}
stretch=TRUE
}
image
{
function=STEPPER
state=NORMAL
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=STEPPER
state=NORMAL
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=STEPPER
state=NORMAL
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=STEPPER
state=NORMAL
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=STEPPER
state=ACTIVE
overlay_file="img/arrow_up-hover.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=STEPPER
state=ACTIVE
overlay_file="img/arrow_down-hover.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=STEPPER
state=ACTIVE
overlay_file="img/arrow_left-hover.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=STEPPER
state=ACTIVE
overlay_file="img/arrow_right-hover.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=STEPPER
state=PRELIGHT
overlay_file="img/arrow_up-hover.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=STEPPER
state=PRELIGHT
overlay_file="img/arrow_down-hover.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=STEPPER
state=PRELIGHT
overlay_file="img/arrow_left-hover.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=STEPPER
state=PRELIGHT
overlay_file="img/arrow_right-hover.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=STEPPER
state=INSENSITIVE
overlay_file="img/arrow_up-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=STEPPER
state=INSENSITIVE
overlay_file="img/arrow_down-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=STEPPER
state=INSENSITIVE
overlay_file="img/arrow_left-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=STEPPER
state=INSENSITIVE
overlay_file="img/arrow_right-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}}}class"GtkScrollbar"style"scrollbar"

style "scrollbarwhite" = "scrollbar"{
engine"pixmap"
{
image
{
function=BOX
orientation=VERTICAL
detail="trough"
file="img/scrollbartroughwhite.png"
border={8,8,10,54}
stretch=TRUE
}
image
{
function=BOX
orientation=HORIZONTAL
detail="trough"
file="img/scrollbartroughwhite_horiz.png"
border={10,54,8,8}
stretch=TRUE}}}
widget_class"*GtkScrolledWindow*GtkHScrollbar"style"scrollbarwhite"
widget_class"*GtkScrolledWindow*GtkVScrollbar"style"scrollbarwhite"
widget_class"*GimpDockbook*Scrollbar"style"scrollbar"
widget_class"*gtkmm__GtkScrolledWindow*Scrollbar"style"scrollbar"
widget_class"*ScintillaObject*Scrollbar*"style"scrollbarwhite"
