style"gtkviews"{
xthickness=0
ythickness=0
GtkButton::inner-border={8,8,8,8}
engine"pixmap"{
image{
function=BOX
shadow=OUT
file="img/treeviewheader.png"
border={0,1,0,1}
stretch=TRUE}
image{
function=BOX
shadow=IN
file="img/treeviewheader-hover.png"
border={0,1,0,1}
stretch=TRUE
}
image
{
function=ARROW
state=INSENSITIVE
detail="arrow"
overlay_file="img/arrow_up-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=INSENSITIVE
detail="arrow"
overlay_file="img/arrow_down-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=INSENSITIVE
detail="arrow"
overlay_file="img/arrow_left-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=INSENSITIVE
detail="arrow"
overlay_file="img/arrow_right-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=NORMAL
detail="arrow"
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=NORMAL
detail="arrow"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=NORMAL
detail="arrow"
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=NORMAL
detail="arrow"
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=ACTIVE
detail="arrow"
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=ACTIVE
detail="arrow"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=ACTIVE
detail="arrow"
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=ACTIVE
detail="arrow"
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=PRELIGHT
detail="arrow"
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=PRELIGHT
detail="arrow"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=PRELIGHT
detail="arrow"
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=PRELIGHT
detail="arrow"
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=TAB
state=INSENSITIVE
detail="optionmenutab"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=TAB
state=NORMAL
detail="optionmenutab"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=TAB
state=PRELIGHT
detail="optionmenutab"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=TAB
state=ACTIVE
detail="optionmenutab"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=NORMAL
expander_style=COLLAPSED
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=PRELIGHT
expander_style=COLLAPSED
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=ACTIVE
expander_style=COLLAPSED
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=INSENSITIVE
expander_style=COLLAPSED
overlay_file="img/arrow_right-insensitive.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=NORMAL
expander_style=SEMI_COLLAPSED
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=PRELIGHT
expander_style=SEMI_COLLAPSED
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=ACTIVE
expander_style=SEMI_COLLAPSED
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=INSENSITIVE
expander_style=SEMI_COLLAPSED
overlay_file="img/arrow_right-insensitive.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=NORMAL
expander_style=EXPANDED
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=PRELIGHT
expander_style=EXPANDED
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=ACTIVE
expander_style=EXPANDED
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=INSENSITIVE
expander_style=EXPANDED
overlay_file="img/arrow_down-insensitive.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=NORMAL
expander_style=SEMI_EXPANDED
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=PRELIGHT
expander_style=SEMI_EXPANDED
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=ACTIVE
expander_style=SEMI_EXPANDED
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=INSENSITIVE
expander_style=SEMI_EXPANDED
overlay_file="img/arrow_down-insensitive.svg"
overlay_stretch=FALSE}}}
widget_class"*.<GtkTreeView>.<GtkButton>*"style"gtkviews"
widget_class"*.<GtkCTree>.<GtkButton>"style"gtkviews"
widget_class"*.<GtkList>.<GtkButton>"style"gtkviews"
widget_class"*.<GtkCList>.<GtkButton>"style"gtkviews"
widget_class"*GtkTreeView*"style"checkbox"
widget_class"*GtkTreeView*"style"radiobox"
widget_class"*GtkTreeView"style"expander"

style"gtkviews2"{
bg[NORMAL]=@window
bg[PRELIGHT]=@window
bg[SELECTED]=@hilight2
bg[ACTIVE]="#b0b0b0"
xthickness=0
ythickness=0}
widget_class"*GtkTreeView*"style"gtkviews2"

style"gtkviews3"{
xthickness=0
ythickness=0
fg[NORMAL]=@windowtext
fg[PRELIGHT]=@windowtext
fg[SELECTED]=@windowtext
fg[ACTIVE]=@windowtext
fg[INSENSITIVE]=@inactivewindowtext}
widget_class"*.<GtkTreeView>.<GtkButton>*"style"gtkviews3"
