widget"*XfceSettingsManagerDialog*GtkHSeparator"style"seperatornone"
widget"*XfceTitledDialog*GtkHSeparator"style"seperatornone"
widget"*ThunarPreferencesDialog*GtkHSeparator"style"seperatornone"
widget"*XfceSettingsManagerDialog*GtkHSeparator"style"seperatornone"
widget"*ThunarPreferencesDialog*GtkHSeparator"style"seperatornone"
widget"*XfceMixerWindow*GtkHSeparator"style"seperatornone"
widget"*PanelItemDialog*GtkHSeparator"style"seperatornone"
widget"*TvmPreferencesDialog*GtkHSeparator"style"seperatornone"
widget"*XfcePluginDialog*GtkHSeparator"style"seperatornone"
widget"*Rstto*GtkHSeparator"style"seperatornone"
widget"*XfceSettingsEditorDialog*GtkHSeparator"style"seperatornone"
widget"*XfceMimeWindow*GtkHSeparator"style"seperatornone"
widget"*XfburnPreferencesDialog*GtkHSeparator"style"seperatornone"
widget"*ExoHelperChooser*GtkHSeparator"style"seperatornone"
widget"*PanelItemDialog*GtkHSeparator"style"seperatornone"
widget_class"*MousepadDocument*Scrollbar"style"scrollbarwhite"

style"xfdesktop"{
font_name="bold"
XfdesktopIconView::shadow-blur-radius=2
XfdesktopIconView::label-alpha=0
XfdesktopIconView::selected-label-alpha=255
XfdesktopIconView::ellipsize-icon-labels=1
XfdesktopIconView::shadow-x-offset=0
XfdesktopIconView::shadow-y-offset=1
XfdesktopIconView::selected-shadow-x-offset=0
XfdesktopIconView::selected-shadow-y-offset=0
XfdesktopIconView::tooltip_size=48
XfdesktopIconView::cell-spacing = 0
XfdesktopIconView::cell-padding = 0
XfdesktopIconView::cell-text-width-proportion = 2
XfdesktopIconView::shadow-color="#555"
XfdesktopIconView::selected-shadow-color=@hilight
fg[NORMAL]="white"
fg[SELECTED]=@windowtext
fg[ACTIVE]=@windowtext}
class"XfdesktopIconView"style"xfdesktop"

## thunar
style "exoicons"{
xthickness=0
ythickness=0
GtkWidget::focus_padding=4
fg[NORMAL]=@hilight2
text[SELECTED]=@windowtext}
widget_class "*ExoIconView*"style "exoicons"
widget_class "*ThunarIconView*ExoIconView"style "exoicons"
widget_class"*ThunarWindow*ThunarIconView*"style"scrollbarwhite"
widget_class"*ThunarWindow*ThunarDetailsView*"style"scrollbarwhite"
widget_class"*ThunarWindow*ThunarCompactView*"style"scrollbarwhite"

style"thunarsidebarpaned"{
xthickness=1
ythickness=1
GtkPaned::handle-size=0
engine"pixmap"{
image{
function=BOX
file="img/separator.png"}}}
widget"ThunarWindow*GtkHPaned"style"thunarsidebarpaned"

style"thunarsidebarcontent"{
engine"pixmap"{
image
{
function=ARROW
state=INSENSITIVE
overlay_file="img/arrow_up-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=INSENSITIVE
overlay_file="img/arrow_down-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=INSENSITIVE
overlay_file="img/arrow_left-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=INSENSITIVE
overlay_file="img/arrow_right-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=NORMAL
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=NORMAL
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=NORMAL
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=NORMAL
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=ACTIVE
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=ACTIVE
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=ACTIVE
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=ACTIVE
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=PRELIGHT
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=PRELIGHT
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=PRELIGHT
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=PRELIGHT
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=INSENSITIVE
overlay_file="img/arrow_up-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=INSENSITIVE
overlay_file="img/arrow_down-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=INSENSITIVE
overlay_file="img/arrow_left-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=INSENSITIVE
overlay_file="img/arrow_right-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=NORMAL
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=NORMAL
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=NORMAL
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=NORMAL
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=ACTIVE
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=ACTIVE
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=ACTIVE
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=ACTIVE
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=PRELIGHT
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=PRELIGHT
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=PRELIGHT
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=PRELIGHT
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=INSENSITIVE
detail="arrow"
overlay_file="img/arrow_up-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=INSENSITIVE
detail="arrow"
overlay_file="img/arrow_down-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=INSENSITIVE
detail="arrow"
overlay_file="img/arrow_left-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=INSENSITIVE
detail="arrow"
overlay_file="img/arrow_right-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=NORMAL
detail="arrow"
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=NORMAL
detail="arrow"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=NORMAL
detail="arrow"
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=NORMAL
detail="arrow"
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=ACTIVE
detail="arrow"
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=ACTIVE
detail="arrow"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=ACTIVE
detail="arrow"
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=ACTIVE
detail="arrow"
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=PRELIGHT
detail="arrow"
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=PRELIGHT
detail="arrow"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=PRELIGHT
detail="arrow"
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=PRELIGHT
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=INSENSITIVE
detail="arrow"
overlay_file="img/arrow_up-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=INSENSITIVE
detail="arrow"
overlay_file="img/arrow_down-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=INSENSITIVE
detail="arrow"
overlay_file="img/arrow_left-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=INSENSITIVE
detail="arrow"
overlay_file="img/arrow_right-insensitive.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=NORMAL
detail="arrow"
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=NORMAL
detail="arrow"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=NORMAL
detail="arrow"
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=NORMAL
detail="arrow"
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=ACTIVE
detail="arrow"
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=ACTIVE
detail="arrow"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=ACTIVE
detail="arrow"
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=ACTIVE
detail="arrow"
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=ARROW
state=PRELIGHT
detail="arrow"
overlay_file="img/arrow_up.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=PRELIGHT
detail="arrow"
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=PRELIGHT
detail="arrow"
overlay_file="img/arrow_left.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=ARROW
state=PRELIGHT
detail="arrow"
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=EXPANDER
state=NORMAL
expander_style=COLLAPSED
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=PRELIGHT
expander_style=COLLAPSED
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=ACTIVE
expander_style=COLLAPSED
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=INSENSITIVE
expander_style=COLLAPSED
overlay_file="img/arrow_right-insensitive.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=NORMAL
expander_style=SEMI_COLLAPSED
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=PRELIGHT
expander_style=SEMI_COLLAPSED
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=ACTIVE
expander_style=SEMI_COLLAPSED
overlay_file="img/arrow_right.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=INSENSITIVE
expander_style=SEMI_COLLAPSED
overlay_file="img/arrow_right-insensitive.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=NORMAL
expander_style=EXPANDED
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=PRELIGHT
expander_style=EXPANDED
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=ACTIVE
expander_style=EXPANDED
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=INSENSITIVE
expander_style=EXPANDED
overlay_file="img/arrow_down-insensitive.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=NORMAL
expander_style=SEMI_EXPANDED
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=PRELIGHT
expander_style=SEMI_EXPANDED
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=ACTIVE
expander_style=SEMI_EXPANDED
overlay_file="img/arrow_down.svg"
overlay_stretch=FALSE
}
image
{
function=EXPANDER
state=INSENSITIVE
expander_style=SEMI_EXPANDED
overlay_file="img/arrow_down-insensitive.svg"
overlay_stretch=FALSE}}}
widget_class "*ThunarTreeView"style "thunarsidebarcontent"
widget_class "*ThunarShortcutsView"style "thunarsidebarcontent"
widget_class"*ThunarTreePane*Scrollbar*"style"scrollbarwhite"
widget_class"*ThunarShortcutsPane*Scrollbar*"style"scrollbarwhite"

style "thunarview"{
xthickness=0
ythickness=1
engine"pixmap"{
image{
function=SHADOW
shadow=IN
file="img/thunar_iconview_border.svg"
stretch=TRUE
border={0,0,1,1}}}}
widget_class "*ThunarIconView*"style "thunarview"
widget_class "*ThunarCompactView*"style "thunarview"
widget_class "*ThunarDetailsView*"style "thunarview"

style "thunarstatusbar"{
xthickness=0
ythickness=0}
widget "*ThunarWindow*Statusbar*"style "thunarstatusbar"

style "xfcenotifyd"{
XfceNotifyWindow::summary-bold=1
XfceNotifyWindow::border-color="#c9c3a3"
XfceNotifyWindow::border-color-hover="#c9c3a3"
XfceNotifyWindow::border-radius=2.0
XfceNotifyWindow::border-width=1
XfceNotifyWindow::border-width-hover=1
bg[NORMAL]="#fbf3c9"}
class "XfceNotifyWindow" style "xfcenotifyd"

style"alttab"{
fg[NORMAL]="white"
fg[SELECTED]="white"
fg[PRELIGHT]=shade (0.8,@hilight)
fg[ACTIVE]=@hilight
fg[INSENSITIVE]="grey"
bg[NORMAL]="black"
bg[PRELIGHT]="black"
bg[SELECTED]="black"
bg[ACTIVE]="black"
bg[INSENSITIVE]="black"
base[NORMAL]="black"
base[PRELIGHT]="black"
base[ACTIVE]="black"
base[SELECTED]="black"
base[INSENSITIVE]="black"
text[NORMAL]="white"
text[PRELIGHT]="white"
text[ACTIVE]="white"
text[SELECTED]="white"
text[INSENSITIVE]="grey"
font_name="bold"
engine"mist"{}}
widget_class"*Xfwm4TabwinWidget*"style"alttab"
widget_class"*Xfwm4TabwinWidget*image*"style"alttab"

